############
### Auth ###
############

### authorize

GET https://bakery-system-backend-nine.vercel.app/api/auth
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### login

POST https://bakery-system-backend-nine.vercel.app/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### logout

GET https://bakery-system-backend-nine.vercel.app/api/auth/logout


#############
### Users ###
#############

### get all users

GET https://bakery-system-backend-nine.vercel.app/api/users
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### get user by id

GET https://bakery-system-backend-nine.vercel.app/api/users/ceb0b46c-9283-4dc2-9971-165fc700fb95
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### create new user

POST https://bakery-system-backend-nine.vercel.app/api/users
Content-Type: application/json
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None

{
  "username": "ahmed",
  "password": "ahmed"
}


### update user

PUT https://bakery-system-backend-nine.vercel.app/api/users/24cf3678-6b42-4b87-968d-a7e4038054d2
Content-Type: application/json
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None

{
  "username": "muhammad",
  "password": "newPassword",
  "role": "STAFF"
}


### delete user

DELETE https://bakery-system-backend-nine.vercel.app/api/users/b0b76520-3705-4ac0-aaea-c5c8990ebf37
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


#################
### Customers ###
#################

### get all customers

GET https://bakery-system-backend-nine.vercel.app/api/customers
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### get customer by id

GET https://bakery-system-backend-nine.vercel.app/api/customers/318528cd-251b-42df-84e1-5eabc183ede3
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### create new customer

POST https://bakery-system-backend-nine.vercel.app/api/customers
Content-Type: application/json
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None

{
  "name": "ahmed",
  "email": "test@test.com",
  "phone": "97570901",
  "address": "123 Main St, City, Country"
}


### update customer

PUT https://bakery-system-backend-nine.vercel.app/api/customers/318528cd-251b-42df-84e1-5eabc183ede3
Content-Type: application/json
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None

{
  "name": "muhammad",
  "phone": "1234567890",
  "address": "street 123"
}


### delete customer

DELETE https://bakery-system-backend-nine.vercel.app/api/customers/e1239588-c2a7-4427-9625-de8a9e1ec9cb
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


################
### Products ###
################

### get all products

GET https://bakery-system-backend-nine.vercel.app/api/products
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### get product by id

GET https://bakery-system-backend-nine.vercel.app/api/products/1
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### delete product

DELETE https://bakery-system-backend-nine.vercel.app/api/products/8
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


##############
### Orders ###
##############

### get all orders

GET https://bakery-system-backend-nine.vercel.app/api/orders
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### get order by id

GET https://bakery-system-backend-nine.vercel.app/api/orders/5
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### place order

POST https://bakery-system-backend-nine.vercel.app/api/orders/place-order
Content-Type: application/json
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None

{
  "customer": "muhammad",
  "status": "PENDING",
  "paymentMethod": "CASH",
  "orderItems": [
    {
      "productId": 1,
      "quantity": 3
    },
    {
      "productId": 2,
      "quantity": 3
    }
  ]
}


### undo order

GET https://bakery-system-backend-nine.vercel.app/api/orders/2/undo-order
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


#################
### Analytics ###
#################

### orders today

GET https://bakery-system-backend-nine.vercel.app/api/analytics/orders-today
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### top product

GET https://bakery-system-backend-nine.vercel.app/api/analytics/top-product
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### lowest stock products

GET https://bakery-system-backend-nine.vercel.app/api/analytics/lowest-stock-products
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None


### week revenue

GET https://bakery-system-backend-nine.vercel.app/api/analytics/week-revenue
cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBjNmJkYWRlLTc0OWEtNGRjOC1iY2U3LTM4MDNhNDRlOWU2YSIsImlhdCI6MTc2MzQ0MjI0MCwiZXhwIjoxNzY0MDQ3MDQwfQ.lnQ-vsBZrbnpYlcLe4u7DyBK-rll7OZfJ2BygvwbWrE; Path=/; HttpOnly; Secure; SameSite=None
