############
### Auth ###
############

### authorize

GET http://localhost:7373/api/auth
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### login

POST http://localhost:7373/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### logout

GET http://localhost:7373/api/auth/logout


#############
### Users ###
#############

### get all users

GET http://localhost:7373/api/users
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### get user by id

GET http://localhost:7373/api/users/ceb0b46c-9283-4dc2-9971-165fc700fb95
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### create new user

POST http://localhost:7373/api/users
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly

{
  "username": "ahmed",
  "password": "ahmed"
}


### update user

PUT http://localhost:7373/api/users/24cf3678-6b42-4b87-968d-a7e4038054d2
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly

{
  "username": "muhammad",
  "password": "newPassword",
  "role": "STAFF"
}


### delete user

DELETE http://localhost:7373/api/users/b0b76520-3705-4ac0-aaea-c5c8990ebf37
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


#################
### Customers ###
#################

### get all customers

GET http://localhost:7373/api/customers
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### get customer by id

GET http://localhost:7373/api/customers/318528cd-251b-42df-84e1-5eabc183ede3
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### create new customer

POST http://localhost:7373/api/customers
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly

{
  "name": "ahmed",
  "email": "test@test.com",
  "phone": "97570901",
  "address": "123 Main St, City, Country"
}


### update customer

PUT http://localhost:7373/api/customers/318528cd-251b-42df-84e1-5eabc183ede3
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly

{
  "name": "muhammad",
  "phone": "1234567890",
  "address": "street 123"
}


### delete customer

DELETE http://localhost:7373/api/customers/e1239588-c2a7-4427-9625-de8a9e1ec9cb
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


################
### Products ###
################

### get all products

GET http://localhost:7373/api/products
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### get product by id

GET http://localhost:7373/api/products/1
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### delete product

DELETE http://localhost:7373/api/products/2
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


##############
### Orders ###
##############

### get all orders

GET http://localhost:7373/api/orders
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### get order by id

GET http://localhost:7373/api/orders/5
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### place order

POST http://localhost:7373/api/orders/place-order
Content-Type: application/json
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly

{
  "customer": "muhammad",
  "status": "PENDING",
  "paymentMethod": "CASH",
  "orderItems": [
    {
      "productId": 1,
      "quantity": 3
    },
    {
      "productId": 2,
      "quantity": 3
    }
  ]
}


### undo order

GET http://localhost:7373/api/orders/2/undo-order
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


#################
### Analytics ###
#################

### orders today

GET http://localhost:7373/api/analytics/orders-today
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### revenue today

GET http://localhost:7373/api/analytics/revenue-today
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### top product

GET http://localhost:7373/api/analytics/top-product
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### lowest stock products

GET http://localhost:7373/api/analytics/lowest-stock-products
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly


### week revenue

GET http://localhost:7373/api/analytics/week-revenue
Cookie: jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxOTY3YTk2LTgxNjItNDczZC04MmNjLTY1MzMzYmE2MzNkZiIsImlhdCI6MTc2MzMyNTY5MiwiZXhwIjoxNzYzOTMwNDkyfQ.gbRR57y97Y0ByIOdOT2H4ESrHXIqCBB-HDMa1cpYjxI; Path=/; HttpOnly
